Resources:
  ProjectRepos:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: project-repos
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:  
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:

  ProjectReposName:
    Description: Name of Project Repos Bucket
    Value: !Ref ProjectRepos
    Export:
      Name: ProjectReposName
    
  ProjectReposArn:
    Description: Arn of Project Repos Bucket
    Value: !GetAtt ProjectRepos.Arn
    Export:
      Name: ProjectReposArn